### ISSUE TITLE
Design Review : per Bryan Stifle

### ISSUE THREAD

**Issue by asangma** [Esri/global-nav#17]
@jonathantneal Posting this issue to track adjustments per Bryan's feedback.

I will be making a PR for some items in this issue.  Some of these will be outside of CSS or are non-issues, but thought it would be better to include all feedback:

- [ ] need to be using globey for logo https://esri.box.com/s/67kk86t8u0e3hddernikw0jjw61elris
- [ ] can't select About menu item when another one is open.
- [ ] on hover, you should see 3px underline (no slide up animation), active simply makes the dropdown viewable
- [ ] where's the dropdown tiles?
- [ ] dropdown item type should be 16px
- [ ] dropdown items on hover need the line to animate left to right (i can show you examples)
- [ ] dropdown items on hover need the arrow to appear
- [ ] need to be able to click off of a dropdown (anywhere) to close it.
- [ ] why are we using #dedede instead of #e0e0e0 on the borders? just curious
- [ ] 1440 grid needs to be honored when not in-app
- [ ] JSON (user's name) needs to be font weight 500.
- [ ] JSON's profile image should have a capital J (first letter of first name) in the avatar image as a default. character should be Avenir Bold 15px, Uppercase, #ffffff , background (circle) should be #005e95
- [ ] Nav items: ArcGIS - Industries - About - Support - Special -- need to be 17px
- [ ] on click, the focus states stay on the app switcher icon and the user profile... let's make it not do that.

- [ ] hover on items (excluding logo) should be #000000 with the 3px bottom rectangle at rgba(0, 121, 193, 0.5)
- [ ] Active on items should be #000000 with the 3px bottom rectangle being #0079c1

---

### Alan's Feedback

- [ ] apps.svg should have color change on `:hover`/`:focus` (How does this affect implementing the SVG?)
